<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Janset.Spike.SDL2.Platform.Generator</RootNamespace>
    <TargetFrameworks></TargetFrameworks>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CppAst" />
    <PackageReference Include="libclang.runtime.win-x64" />
    <PackageReference Include="libClangSharp.runtime.win-x64" />
  </ItemGroup>
</Project>
