using System.Text;
using CppAst;

namespace Janset.Sdl2.AlimerSpike.Generator;

internal sealed record EmissionRequest(
    string Family,
    string NativeClassName,
    string LibraryName,
    string OwnedPrefix,
    IReadOnlyList<string> ExcludedFunctions);

internal sealed record EmissionResult(
    int Seen,
    int Emitted,
    IReadOnlyList<SkipEntry> Skips);

// One emit per family. Emits a partial-class file with [DllImport] entries
// for every CppFunction whose return and parameter types map cleanly via
// Sdl2TypeNameMapper. Unmappable functions are recorded with a skip reason —
// the spike never invents fake bindings (constitution §"Layer Contract").
//
// Mirrors the surface shape of
// build/_build/Targets/GenerateBindings/Emit/RawAbi/RawAbiCommandEmitter.cs
// but kept tiny: no platform attribution, no per-view dedup, no auto-handle
// classification. The output is just internal-raw-ABI prose so a compile
// check and an oracle compare are possible.
internal static class Sdl2RawAbiEmitter
{
    public static EmissionResult Emit(
        Sdl2SpikeOptions options,
        EmissionRequest request,
        IReadOnlyList<CppCompilation> compilations)
    {
        var seenFunctions = new HashSet<string>(StringComparer.Ordinal);
        var emittedNames = new SortedSet<string>(StringComparer.Ordinal);
        var skips = new List<SkipEntry>();
        var excluded = new HashSet<string>(request.ExcludedFunctions, StringComparer.Ordinal);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine();
        sb.AppendLine($"namespace Janset.Sdl2.AlimerSpike.Output.Internal;");
        sb.AppendLine();
        sb.AppendLine($"internal static unsafe partial class {request.NativeClassName}");
        sb.AppendLine("{");

        foreach (var compilation in compilations)
        {
            foreach (var function in compilation.Functions)
            {
                if (!function.Name.StartsWith(request.OwnedPrefix, StringComparison.Ordinal))
                {
                    continue;
                }

                if (!seenFunctions.Add(function.Name))
                {
                    continue;
                }

                var header = Path.GetFileName(function.SourceFile ?? "<unknown>");

                if (excluded.Contains(function.Name))
                {
                    skips.Add(new SkipEntry(request.Family, header, function.Name, SkipReason.UnsupportedValueType, "manifest/spike excluded"));
                    continue;
                }

                // CppAst doesn't surface a CppFunction.IsVariadic property in this
                // version, but variadics show up via CppEllipsisType in the
                // parameter list — Sdl2TypeNameMapper returns SkipReason.UnknownPrimitive
                // (or similar) for that and the function gets recorded below.
                if (!TryEmitFunction(function, request, sb, out var skipReason, out var skipDetail))
                {
                    skips.Add(new SkipEntry(request.Family, header, function.Name, skipReason, skipDetail));
                    continue;
                }

                emittedNames.Add(function.Name);
            }
        }

        sb.AppendLine("}");

        if (options.Emit)
        {
            var outputDir = Path.Combine(options.GeneratedRoot, "Internal");
            Directory.CreateDirectory(outputDir);
            var outputFile = Path.Combine(outputDir, request.NativeClassName + ".g.cs");
            File.WriteAllText(outputFile, sb.ToString(), Encoding.UTF8);
        }

        return new EmissionResult(seenFunctions.Count, emittedNames.Count, skips);
    }

    private static bool TryEmitFunction(
        CppFunction function,
        EmissionRequest request,
        StringBuilder sb,
        out SkipReason skipReason,
        out string skipDetail)
    {
        var returnType = Sdl2TypeNameMapper.Map(function.ReturnType);
        if (returnType.IsSkip)
        {
            skipReason = returnType.Reason;
            skipDetail = $"return type unmapped";
            return false;
        }

        var parameterParts = new List<string>(function.Parameters.Count);
        for (var index = 0; index < function.Parameters.Count; index++)
        {
            var parameter = function.Parameters[index];
            var mapped = Sdl2TypeNameMapper.Map(parameter.Type);
            if (mapped.IsSkip)
            {
                skipReason = mapped.Reason;
                skipDetail = $"parameter[{index}] '{parameter.Name}' unmapped";
                return false;
            }
            var safeName = Sdl2TypeNameMapper.SafeIdentifier(parameter.Name, index);
            parameterParts.Add($"{mapped.ManagedName} {safeName}");
        }

        sb.AppendLine($"    [DllImport(\"{request.LibraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"{function.Name}\")]");
        sb.AppendLine($"    internal static extern {returnType.ManagedName} {function.Name}({string.Join(", ", parameterParts)});");
        sb.AppendLine();

        skipReason = SkipReason.None;
        skipDetail = string.Empty;
        return true;
    }
}
