using System.Globalization;
using System.Text;
using CppAst;

namespace Janset.Spike.SDL2.Gfx.Generator;

internal static class Program
{
    private const string RepoRoot = @"E:/repos/my-projects/janset2d/sdl2-cs-bindings";
    private const string VcpkgIncludeRoot = RepoRoot + "/vcpkg_installed/x64-windows-hybrid/include";
    private const string SDL2IncludeDir = VcpkgIncludeRoot + "/SDL2";
    private const string OutputPath = RepoRoot + "/tools/binding-spike/cppast/bindings/Generated/SDL2_gfx.cs";

    private static readonly string[] HeaderFiles =
    [
        "SDL2_gfxPrimitives.h",
        "SDL2_framerate.h",
        "SDL2_imageFilter.h",
        "SDL2_rotozoom.h"
    ];

    // Opaque SDL pointer types remapped to IntPtr (matches ClangSharp spike's policy).
    private static readonly HashSet<string> OpaquePointerTypes =
        new(StringComparer.Ordinal) { "SDL_Renderer", "SDL_Surface", "SDL_Texture" };

    // Macros excluded from constant emission (M_PI duplicated across two headers).
    private static readonly HashSet<string> ExcludedMacros =
        new(StringComparer.Ordinal) { "M_PI" };

    public static int Main()
    {
        var options = new CppParserOptions
        {
            ParseMacros = true,
            SystemIncludeFolders = { VcpkgIncludeRoot },
            Defines = { "SDL_DECLSPEC=", "__PRFCHWINTRIN_H=1" }
        };

        var headerPaths = HeaderFiles.Select(h => Path.Combine(SDL2IncludeDir, h)).ToList();
        var compilation = CppParser.ParseFiles(headerPaths, options);

        if (compilation.HasErrors)
        {
            Console.Error.WriteLine("Parse errors:");
            foreach (var msg in compilation.Diagnostics.Messages.Where(m => m.Type == CppLogMessageType.Error))
            {
                Console.Error.WriteLine($"  {msg}");
            }
            return 1;
        }

        // Only emit symbols that live inside our 4 target headers (not transitively pulled SDL2 core).
        var targetHeaderPaths = headerPaths
            .Select(p => p.Replace('\\', '/'))
            .ToHashSet(StringComparer.OrdinalIgnoreCase);

        bool InTargetHeader(CppElement element) =>
            element.SourceFile is not null
            && targetHeaderPaths.Contains(element.SourceFile.Replace('\\', '/'));

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// CppAst-spike-generated SDL2_gfx bindings.");
        sb.AppendLine("// Source headers: SDL2_gfxPrimitives.h + SDL2_framerate.h + SDL2_imageFilter.h + SDL2_rotozoom.h");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine();
        sb.AppendLine("namespace Janset.Spike.SDL2.Gfx;");
        sb.AppendLine();

        // Emit structs (POD records like FPSmanager)
        var structs = compilation.Classes
            .Where(c => c.ClassKind == CppClassKind.Struct && c.Fields.Count > 0 && InTargetHeader(c))
            .ToList();

        foreach (var cppStruct in structs)
        {
            sb.AppendLine("[StructLayout(LayoutKind.Sequential)]");
            sb.AppendLine($"public struct {cppStruct.Name}");
            sb.AppendLine("{");
            foreach (var field in cppStruct.Fields)
            {
                sb.AppendLine($"    public {MapType(field.Type)} {field.Name};");
            }
            sb.AppendLine("}");
            sb.AppendLine();
        }

        // Open the static class for functions + constants
        sb.AppendLine("public static unsafe partial class SDL_gfx");
        sb.AppendLine("{");
        sb.AppendLine("    private const string LibName = \"SDL2_gfx\";");

        // Emit value-like macros as constants
        var emittedMacros = new HashSet<string>(StringComparer.Ordinal);
        foreach (var macro in compilation.Macros
                     .Where(InTargetHeader)
                     .Where(m => !ExcludedMacros.Contains(m.Name))
                     .Where(m => m.Parameters is null || m.Parameters.Count == 0))
        {
            if (!emittedMacros.Add(macro.Name)) continue;
            if (TryEmitMacroConstant(macro, out var emitted))
            {
                sb.AppendLine();
                sb.AppendLine($"    {emitted}");
            }
        }

        // Emit function P/Invokes (filter to target headers only)
        var functions = compilation.Functions
            .Where(InTargetHeader)
            .Where(f => !string.IsNullOrEmpty(f.Name))
            .ToList();

        foreach (var func in functions)
        {
            var returnType = MapType(func.ReturnType);
            var parameters = string.Join(", ",
                func.Parameters.Select(p => $"{MapType(p.Type)} {SafeIdentifier(p.Name)}"));

            sb.AppendLine();
            sb.AppendLine("    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]");
            sb.AppendLine($"    public static extern {returnType} {func.Name}({parameters});");
        }

        sb.AppendLine("}");

        Directory.CreateDirectory(Path.GetDirectoryName(OutputPath)!);
        File.WriteAllText(OutputPath, sb.ToString());

        Console.WriteLine($"Generated {functions.Count} functions, {structs.Count} structs, {emittedMacros.Count} macros to {OutputPath}");
        return 0;
    }

    private static string SafeIdentifier(string name)
    {
        if (string.IsNullOrEmpty(name)) return "@_";
        return name switch
        {
            "ref" or "out" or "in" or "params" or "object" or "string" or "event" => "@" + name,
            _ => name
        };
    }

    private static bool TryEmitMacroConstant(CppMacro macro, out string emitted)
    {
        emitted = string.Empty;
        if (string.IsNullOrWhiteSpace(macro.Value)) return false;

        var value = macro.Value.Trim();
        var cleaned = value.TrimEnd('u', 'U', 'l', 'L', 'f', 'F');

        if (int.TryParse(cleaned, NumberStyles.Integer, CultureInfo.InvariantCulture, out var intVal))
        {
            emitted = $"public const int {macro.Name} = {intVal};";
            return true;
        }

        if (cleaned.StartsWith("0x", StringComparison.OrdinalIgnoreCase)
            && uint.TryParse(cleaned[2..], NumberStyles.HexNumber, CultureInfo.InvariantCulture, out var hexVal))
        {
            emitted = $"public const uint {macro.Name} = 0x{hexVal:X};";
            return true;
        }

        if (double.TryParse(cleaned, NumberStyles.Float, CultureInfo.InvariantCulture, out var doubleVal))
        {
            emitted = $"public const double {macro.Name} = {doubleVal.ToString("R", CultureInfo.InvariantCulture)};";
            return true;
        }

        if (value.StartsWith('"') && value.EndsWith('"'))
        {
            emitted = $"public const string {macro.Name} = {value};";
            return true;
        }

        return false;
    }

    private static string MapType(CppType type)
    {
        while (type is CppQualifiedType qt) type = qt.ElementType;

        return type switch
        {
            CppPrimitiveType prim => MapPrimitive(prim),
            CppPointerType ptr => MapPointer(ptr),
            CppTypedef td => MapTypedef(td),
            CppArrayType arr => MapPointer(new CppPointerType(arr.ElementType)),
            CppClass cls => cls.Name,
            _ => "IntPtr"
        };
    }

    private static string MapPrimitive(CppPrimitiveType prim) => prim.Kind switch
    {
        CppPrimitiveKind.Void => "void",
        CppPrimitiveKind.Bool => "byte",
        CppPrimitiveKind.Char => "sbyte",
        CppPrimitiveKind.WChar => "char",
        CppPrimitiveKind.Short => "short",
        CppPrimitiveKind.Int => "int",
        CppPrimitiveKind.LongLong => "long",
        CppPrimitiveKind.UnsignedChar => "byte",
        CppPrimitiveKind.UnsignedShort => "ushort",
        CppPrimitiveKind.UnsignedInt => "uint",
        CppPrimitiveKind.UnsignedLongLong => "ulong",
        CppPrimitiveKind.Float => "float",
        CppPrimitiveKind.Double => "double",
        CppPrimitiveKind.Long => "int",          // Windows LLP64: long is 32-bit
        CppPrimitiveKind.UnsignedLong => "uint",
        _ => "IntPtr"
    };

    private static string MapPointer(CppPointerType ptr)
    {
        var element = ptr.ElementType;
        while (element is CppQualifiedType qt) element = qt.ElementType;

        return element switch
        {
            CppPrimitiveType { Kind: CppPrimitiveKind.Void } => "IntPtr",
            CppPrimitiveType prim => MapPrimitive(prim) + "*",
            // CppAst can surface opaque SDL types as either CppTypedef OR CppClass
            // depending on whether libclang resolved the typedef chain.
            CppTypedef td when OpaquePointerTypes.Contains(td.Name) => "IntPtr",
            CppClass cls when OpaquePointerTypes.Contains(cls.Name) => "IntPtr",
            CppTypedef td => MapTypedefPointer(td),
            CppClass cls => cls.Name + "*",
            _ => "IntPtr"
        };
    }

    private static string MapTypedefPointer(CppTypedef td)
    {
        var element = td.ElementType;
        while (element is CppQualifiedType qt) element = qt.ElementType;

        if (element is CppPrimitiveType prim) return MapPrimitive(prim) + "*";
        if (element is CppTypedef nested) return MapTypedefPointer(nested);
        return td.Name + "*";
    }

    private static string MapTypedef(CppTypedef td) => td.Name switch
    {
        "Sint8" => "sbyte",
        "Uint8" => "byte",
        "Sint16" => "short",
        "Uint16" => "ushort",
        "Sint32" => "int",
        "Uint32" => "uint",
        "Sint64" => "long",
        "Uint64" => "ulong",
        "SDL_bool" => "byte",
        "size_t" => "nuint",
        "ptrdiff_t" => "nint",
        _ => MapType(td.ElementType)
    };
}
