name: Prepare Native Assets for Linux

on:
  workflow_call:
    inputs:
      triplet:
        required: true
        type: string
      rid:
        required: true
        type: string
      vcpkg-cache-path:
        required: true
        type: string
      vcpkg-feature-flags:
        required: true
        type: string
      runner:
        required: true
        type: string
      container-image:
        required: true
        type: string

jobs:
  native:
    name: Native Build Linux (${{ inputs.container-image }} / ${{ inputs.triplet }})
    runs-on: ${{ inputs.runner }}
    container: ${{ inputs.container-image }}
    defaults: { run: { shell: bash } }

    steps:
      # — prerequisites just for the container —
      - name: Install Build Prerequisites
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
            git wget curl build-essential pkg-config tar unzip zip ca-certificates python3 \
            python3-pip python3-jinja2 bison autoconf automake autoconf-archive libltdl-dev libtool
          update-ca-certificates # Ensure certificates are updated
        env: { DEBIAN_FRONTEND: noninteractive }

      # — checkout and vcpkg build —
      - uses: actions/checkout@v4
        with: { submodules: recursive, fetch-depth: 0 }

      - name: Run Vcpkg Setup Action
        uses: ./.github/actions/vcpkg-setup # Uses the composite action
        with:
          runner-os: ${{ inputs.runner }}
          cache-key-base: ${{ inputs.container-image }}
          triplet: ${{ inputs.triplet }}
          vcpkg-cache-path: ${{ inputs.vcpkg-cache-path }}
          vcpkg-feature-flags: ${{ inputs.vcpkg-feature-flags }}

      # — archive the *native* artefacts (whole folder) —
      - name: Upload vcpkg_installed
        uses: actions/upload-artifact@v4
        with:
          name: vcpkg-installed-${{ inputs.triplet }}
          path: vcpkg_installed
          retention-days: 1

  managed:
    name: Managed Build Linux (${{ inputs.triplet }})
    needs: native # Run after native build completes
    runs-on: ${{ inputs.runner }}
    defaults: { run: { shell: bash } }
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

    steps:
      # — checkout repo (bind‑mount workspace) —
      - uses: actions/checkout@v4
        with: { submodules: recursive, fetch-depth: 0 }

      # — pull back the native artefacts built in the container —
      - name: Download vcpkg_installed
        uses: actions/download-artifact@v4
        with:
          name: vcpkg-installed-${{ inputs.triplet }} # Use input triplet in name
          path: vcpkg_installed         # same relative location as original

      # — .NET SDKs —
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.nuget/packages
          key:  nuget-${{ runner.os }}-${{ hashFiles('./build/_build/packages.lock.json') }}

      - name: Restore Cake host packages
        run: dotnet restore ./build/_build/Build.csproj --use-lock-file

      - name: Build Cake host
        run: dotnet build ./build/_build/Build.csproj --configuration Release --no-restore

      - name: Run Cake Build (Info Task)
        run: ./build/_build/bin/Release/net9.0/Build --target Info --verbosity diagnostic
